Marina_Page_Beta/flask_app/blog/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_app import db, bcrypt
from flask_app.blog.forms import PostBlogForm
from flask_app.models import User, Blog_Post
from flask_login import login_required, current_user


blog_bp = Blueprint('blog_bp', __name__)


### View Blog ###
@blog_bp.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    posts = Blog_Post.query.order_by(Blog_Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('blog.html', posts=posts)


## post new blog post ##

@blog_bp.route("/Blog_Post/new", methods=['GET', 'POST'])
@login_required
def new_blog_post():
    form = PostBlogForm()
    if form.validate_on_submit():
        post = Blog_Post(title=form.title.data,
                        content=form.content.data,
                        author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('blog_bp.blog'))
    return render_template('post_update_blog.html',
                            title='New Post',
                            form=form,
                            legend='New Post')


### Route for every blog post to have unique page ###
@blog_bp.route("/Blog_Post/<int:post_id>")
def blog_by_id(post_id):
    post = Blog_Post.query.get_or_404(post_id)
    return render_template('blog_by_id.html', title=post.title, post=post)


## Update Blog Posts ##

@blog_bp.route("/Blog_Post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_blog_post(post_id):
    # making sure the post is real or sends user to 404 page
    post = Blog_Post.query.get_or_404(post_id)

    # making sure the person posting is the actual author
    # 403 is forbidden route
    if post.author != current_user:
        abort(403)
    form = PostBlogForm()

    # making sure the logic for form submission (updating) is good
    if form.validate_on_submit():
        # then we just update our post
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()

        flash('Your post has been updated!', 'success')
        return redirect(url_for('blog_bp.blog_by_id', post_id=post.id))


    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('post_update_blog.html', title="Update Post",
                            form=form, legend='Update Post')

# -- Delete route --
# only accepting POST requests since
# this will be only shown on the delete post modal
@blog_bp.route("/Blog_Post/<int:post_id>/delete", methods = ['POST'])
@login_required
def delete_blog_post(post_id):
    post = Blog_Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    # adding deletion of post to the database session
    db.session.delete(post)
    # commiting the deletion
    db.session.commit()
    # flash message telling user the post has been delete
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main_bp.home'))




@blog_bp.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Blog_Post.query.filter_by(author=user)\
        .order_by(Blog_Post.date_posted.desc())\
        .paginate(page=page, per_page=5)

    return render_template('user_posts.html', posts=posts, user=user)

Marina_Page_Beta/flask_app/gallery/routes.py

from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_app import db, bcrypt
from flask_app.gallery.forms import PostGalleryForm
from flask_app.gallery.utils import save_gallery_picture
from flask_app.models import Gallery_Post
from flask_login import current_user, login_required

# TESTING #
from flask_app.models import Gallery_Page_Update

gallery_bp = Blueprint('gallery_bp', __name__)


@gallery_bp.route("/gallery")
def gallery():
    page_update = Gallery_Page_Update.query.order_by(Gallery_Page_Update.date_posted.desc()).first()
    page = request.args.get('page', 1, type=int)
    posts = Gallery_Post.query.order_by(Gallery_Post.date_posted.desc()).paginate(page=page, per_page=12)
    return render_template('gallery.html', posts=posts, page_update=page_update)



@gallery_bp.route("/gallery_Post/new", methods=['GET', 'POST'])
@login_required
def new_gallery_post():
    form = PostGalleryForm()
    if form.validate_on_submit():
        picture_saved = save_gallery_picture(form.gallery_picture.data)
        post = Gallery_Post(title=form.title.data,
                            gallery_picture=picture_saved,
                            content=form.content.data,
                            price=form.price.data,
                            author=current_user)

        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('gallery_bp.gallery'))
    return render_template('post_update_gallery.html', title='New Image Post',form=form, legend='New Image Post')



@gallery_bp.route("/gallery_post/<int:post_id>")
def gallery_by_id(post_id):
    post = Gallery_Post.query.get_or_404(post_id)
    return render_template('gallery_by_id.html', title=post.title, post=post)


@gallery_bp.route("/gallery_Post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_gallery_post(post_id):
    # making sure the post is real or sends user to 404 page
    post = Gallery_Post.query.get_or_404(post_id)

    # making sure the person posting is the actual author
    # 403 is forbidden route
    if post.author != current_user:
        abort(403)
    form = PostGalleryForm()

    # making sure the logic for form submission (updating) is good
    if form.validate_on_submit():
        # then we just update our post
        picture_saved = save_gallery_picture(form.gallery_picture.data)
        post.title = form.title.data
        post.gallery_picture = picture_saved
        post.content = form.content.data
        post.price = form.price.data
        db.session.commit()

        # flashing a message letting the user know that the post has been updated
        flash('Your post has been updated!', 'success')
        # this redirects the user back to the post they just updated
        # notice how the post_id is retreived
        return redirect(url_for('gallery_bp.gallery_by_id', post_id=post.id))


    # populating the title and content of the post that you want to update
    # (this way it's not deleting the previous post, just allowing the user
    # to update it)
    # we'll "only" display this if the request is a 'GET' request
    # (which technically it will be everytime until is a 'POST' so this
    # looks like it's more for structure and logic)
    elif request.method == 'GET':
        form.title.data = post.title
        form.gallery_picture.data = post.gallery_picture
        form.content.data = post.content
        form.price.data = post.price

    # notice how the return render_template is always pushed first,
    # then all the if/else get run (this is the same in every route, python
    # indentation is why it's noticeable, how would it be done in C+ or JS?)
    return render_template('post_update_gallery.html', title="Update Post",
                            form=form, legend='Update Post')

# -- Delete route --
@gallery_bp.route("/gallery_Post/<int:post_id>/delete", methods = ['POST'])
@login_required
def delete_gallery_post(post_id):
    post = Gallery_Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    # adding deletion of post to the database session
    db.session.delete(post)
    # commiting the deletion
    db.session.commit()
    # flash message telling user the post has been delete
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main_bp.home'))

Marina_Page_Beta/flask_app/portfolio/routes.py
from flask import (render_template, url_for,
                    flash, redirect,
                    request, abort,
                    Blueprint)
from flask_app import db, bcrypt
from flask_app.portfolio.forms import PostPortfolioForm
from flask_app.models import User, Portfolio_Post, Portfolio_Page_Update
from flask_app.portfolio.utils import save_portfolio_picture
from flask_login import  current_user, login_required

portfolio_bp = Blueprint('portfolio_bp', __name__)

### View the Portfolio ###
@portfolio_bp.route("/portfolio")
def portfolio():
    page_update = Portfolio_Page_Update.query.order_by(Portfolio_Page_Update.date_posted.desc()).first()
    page = request.args.get('page', 1, type=int)
    posts = Portfolio_Post.query.order_by(Portfolio_Post.date_posted.desc()).paginate(page=page, per_page=12)
    return render_template('portfolio.html', posts=posts, page_update=page_update)


### Post to the Portfolio ###
@portfolio_bp.route("/Portfolio_Post/new", methods=['GET', 'POST'])
@login_required
def new_portfolio_post():
    form = PostPortfolioForm()
    if form.validate_on_submit():
        picture_saved = save_portfolio_picture(form.portfolio_picture.data)
        post = Portfolio_Post(title=form.title.data,
                            portfolio_picture=picture_saved,
                            content=form.content.data,
                            author=current_user)

        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('portfolio_bp.portfolio'))
    return render_template('post_update_portfolio.html', title='New Image Post',form=form, legend='New Image Post')



@portfolio_bp.route("/portfolio_post/<int:post_id>")
def portfolio_by_id(post_id):
    post = Portfolio_Post.query.get_or_404(post_id)
    return render_template('portfolio_by_id.html', title=post.title, post=post)


@portfolio_bp.route("/Portfolio_Post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_portfolio_post(post_id):
    # making sure the post is real or sends user to 404 page
    post = Portfolio_Post.query.get_or_404(post_id)

    # making sure the person posting is the actual author
    # 403 is forbidden route
    if post.author != current_user:
        abort(403)
    form = PostPortfolioForm()

    # making sure the logic for form submission (updating) is good
    if form.validate_on_submit():
        # then we just update our post
        picture_saved = save_portfolio_picture(form.portfolio_picture.data)
        post.title = form.title.data
        post.portfolio_picture = picture_saved
        post.content = form.content.data
        db.session.commit()

        # flashing a message letting the user know that the post has been updated
        flash('Your post has been updated!', 'success')
        # this redirects the user back to the post they just updated
        # notice how the post_id is retreived
        return redirect(url_for('portfolio_bp.portfolio_by_id', post_id=post.id))


    # populating the title and content of the post that you want to update
    # (this way it's not deleting the previous post, just allowing the user
    # to update it)
    # we'll "only" display this if the request is a 'GET' request
    # (which technically it will be everytime until is a 'POST' so this
    # looks like it's more for structure and logic)
    elif request.method == 'GET':
        form.title.data = post.title
        form.portfolio_picture.data = post.portfolio_picture
        form.content.data = post.content

    # notice how the return render_template is always pushed first,
    # then all the if/else get run (this is the same in every route, python
    # indentation is why it's noticeable, how would it be done in C+ or JS?)
    return render_template('post_update_portfolio.html', title="Update Post",
                            form=form, legend='Update Post')

# -- Delete route --
@portfolio_bp.route("/Portfolio_Post/<int:post_id>/delete", methods = ['POST'])
@login_required
def delete_portfolio_post(post_id):
    post = Portfolio_Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    # adding deletion of post to the database session
    db.session.delete(post)
    # commiting the deletion
    db.session.commit()
    # flash message telling user the post has been delete
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main_bp.home'))

Marina_Page_Beta/flask_app/users/routes.py
from flask import (render_template, url_for,
                    flash, redirect,
                    request, abort,
                    Blueprint)
from flask_app import db, bcrypt
from flask_app.users.forms import (RegistrationForm, LoginForm,
                                    RequestResetForm, UpdateAccountForm,
                                    ResetPasswordForm)
from flask_app.users.utils import save_user_picture, send_reset_email
from flask_app.models import User

from flask_login import login_user, current_user, logout_user, login_required


users_bp = Blueprint('users_bp', __name__)

### Register New User
# REMOVE ONCE YOUR ARTISTS + ADMIN ARE REGISTERED
@users_bp.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users_bp.login'))
    return render_template('register.html', title='Register', form=form)


### Login (change the /route to conseal n00bz from trying to hack you) ###
@users_bp.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            # this pushes the user to the page they were trying to click on
            # before getting force redirected to the login page
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main_bp.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


### Logout ###
@users_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main_bp.home'))




@users_bp.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_user_picture(form.picture.data)
            current_user.user_picture = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        hashed_password = bcrypt.generate_password_hash(form.confirm_password.data).decode('utf-8')
        current_user.password = hashed_password
        db.session.commit()

        flash('Your account has been updated!', 'success')
        return redirect(url_for('users_bp.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    user_picture = url_for('static', filename='profile_pics/' + current_user.user_picture)
    return render_template('account.html', title='Account',
                           user_picture=user_picture, form=form)



@users_bp.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users_bp.login'))
    return render_template('reset_request.html', title='Reset Password?', form=form)


@users_bp.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users_bp.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users_bp.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

Marina_Page_Beta/flask_app/templates/bio.html
{% extends "layout.html" %}

{% block content %}

{% if bio_update %}

  <img class="rounded-circle bio-image" src="{{ url_for('static', filename='bio_photos/' + bio_update.bio_photo) }}">


  <h1 class="text-left">{{ bio_update.title }}</h1>
  <p class="text-muted text-justify">{{ bio_update.content }}</p>

{% else %}

  <h1 class="text-center">Bio</h1>
  <p class="text-muted text-justify">Ambitioni dedisse scripsisse iudicaretur. 'Cras mattis iudicium purus sit amet fermentum. Donec sed odio operae, eu vulputate felis rhoncus. Praeterea iter est quasdam res quas ex communi. At nos hinc posthac, sitientis piros Afros. Petierunt uti sibi concilium totius Galliae in diem certam indicere. Cras mattis iudicium purus sit amet fermentum.</p>

{% endif %}

{% if current_user.is_authenticated %}
  <div class="container mt-4">
    <a class="btn btn-outline-secondary btn-md mt-1 mb-1" href="{{ url_for('main_bp.update_bio_page') }}">Update</a>
  </div>
{% endif %}


{% endblock content %}

Marina_Page_Beta/flask_app/templates/blog.html
{% extends "layout.html" %}
{% block blog %}
    {% for post in posts.items %}
        <article class="media content-section">
          <div class="media-body mt-4 mb-2">
            <div class="article-metadata">
              <!-- <a class="mr-2 mt-4" href="{{ url_for('blog_bp.user_posts', username=post.author.username) }}"> {{ post.author.username }}</a> -->

              <!-- This is if a user requests to have the date shown -->
              <!-- <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small> -->

            </div>
            <h2><a class="article-title" href="{{ url_for('blog_bp.blog_by_id', post_id=post.id)}}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|truncate(length=300, killwords=True) }}  </p>
              {% if post.content|length > 300 %}
              <a class="gray" href="{{ url_for('blog_bp.blog_by_id', post_id=post.id)}}">(...read more)</a>
              {% else %}
              {% endif %}
          </div>
        </article>
    {% endfor %}

    <!-- pagination logic -->
    <div class="mt-5">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
                {% if posts.page == page_num %}
                  <a class="btn btn-info mb-4" href="{{ url_for('blog_bp.blog', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                  <a class="btn btn-outline-info mb-4" href="{{ url_for('blog_bp.blog', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
          {% else %}
                  ...
          {% endif %}
    {% endfor %}
    </div>

    {% if current_user.is_authenticated %}
      <div>
        <a class="btn btn-outline-info btn-md mt-1 mb-1" href="{{ url_for('blog_bp.new_blog_post') }}">New Blog Post</a>
      </div>
    {% endif %}

{% endblock blog %}

Marina_Page_Beta/flask_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- using Bootstrap -->
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


  <!-- Font awesome 5 for Gliphs -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- Google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">


  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css')}}">


  {% if title %}

      <title> Artist Name - {{ title }} </title>

  {% else %}

      <title> Artist Name </title>

  {% endif %}

  <!-- ICON AT THE TOP OF THE WEBPAGE LINK -->
  <link rel="icon" href="{{ url_for('static', filename='profile_pics/default.jpg')}}">

</head>

  <header class="site-header topOfPage">
    <nav class="navbar navbar-expand-md navbar-dark bg-nav-color fixed-top">
       <div class="container">
           <a class="navbar-brand mr-4 ml-4" href="/">
           <!-- <img class="brand-img" src="{{ url_for('static', filename='home_photos/brand_image.jpg')}}" alt=""> -->
           Marina</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">

                <ul class="navbar-nav mr-auto">
                  {% if current_user.is_authenticated %}
                                <li class="nav-item dropdown">
                                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Site Navigation
                                  </a>
                                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ url_for('portfolio_bp.portfolio') }}">Portfolio</a>
                                    <a class="dropdown-item" href="{{ url_for('gallery_bp.gallery') }}">Gallery</a>
                                    <a class="dropdown-item" href="{{ url_for('blog_bp.blog') }}">Writings</a>

                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ url_for('main_bp.home') }}">Home</a>
                                    <a class="dropdown-item" href="{{ url_for('main_bp.bio') }}">Bio</a>
                                    <a class="dropdown-item text-center" href="{{ url_for('main_bp.map') }}">Shop Location</a>
                                    <a class="dropdown-item text-center" href="{{ url_for('main_bp.contact') }}">Contact Us</a>

                                  </div>
                                </li>

                                <li class="nav-item dropdown">
                                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Post/Edit
                                  </a>
                                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ url_for('portfolio_bp.new_portfolio_post') }}">New Portfolio</a>
                                    <a class="dropdown-item" href="{{ url_for('gallery_bp.new_gallery_post') }}">New Gallery</a>
                                    <a class="dropdown-item" href="{{ url_for('blog_bp.new_blog_post') }}">New Blog Post</a>

                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ url_for('main_bp.update_home_page') }}">Edit Home Page</a>
                                    <a class="dropdown-item" href="{{ url_for('main_bp.update_bio_page') }}">Edit Bio Page</a>
                                    <a class="dropdown-item" href="{{ url_for('main_bp.update_gallery') }}">Edit Gallery Page</a>
                                    <a class="dropdown-item" href="{{ url_for('main_bp.update_portfolio') }}">Edit Portfolio Page</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ url_for('users_bp.account') }}">Edit Account</a>

                                  </div>
                                </li>
                                <li class="nav-item">
                                  <a class="nav-item nav-link" href="{{ url_for('users_bp.logout') }}">Logout</a>
                                </li>
                      {% else %}
                              <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main_bp.home') }}">Home</a>
                              </li>

                              <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('portfolio_bp.portfolio') }}">Portfolio</a>
                              </li>

                              <li class="nav-item">
                                <a class="nav-link"  href="{{ url_for('gallery_bp.gallery') }}">Gallery</a>
                              </li>

                              <li class="nav-item">
                                <a class="nav-link"  href="{{ url_for('blog_bp.blog') }}">Writings</a>
                              </li>

                              <li class="nav-item">
                                <a class="nav-link"  href="{{ url_for('main_bp.bio') }}">Bio</a>
                              </li>

                              <li class="nav-item">
                                <a class="nav-link text-center"  href="{{ url_for('main_bp.contact') }}">Contact Us</a>
                              </li>


                              <li class="nav-item">
                                <a class="nav-link text-center"  href="{{ url_for('main_bp.map') }}">Shop Location</a>
                              </li>

<!-- REMOVE ONCE YOUR ARTISTS + ADMIN ARE REGISTERED -->
                              <li class="nav-item">
                                <a class="nav-item nav-link" href="{{ url_for('users_bp.register') }}">Register</a>
                              </li>
                              <li class="nav-item">
                                <a class="nav-item nav-link" href="{{ url_for('users_bp.login') }}">Login</a>
                              </li>
                      {% endif %}
                              </ul>
                            </div>
          </div>
        </div>
    </nav>
  </header>


<!-- POPUPS PRIMARILY FOR LOGGED IN ARTIST TO CONFIRM THAT SOMETHING HAS HAPPENED -->
  <main role="main" class="container mb-4">
            <div class="row">
              <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories='true') %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                              {{ message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
              </div>
          </div>

      <div class="container pt-4">

        {% block content %}
        {% endblock content %}

        {% block home %}
        {% endblock home %}

        {% block blog %}
        {% endblock blog %}

        {% block gallery %}
        {% endblock gallery %}

        {% block portfolio %}
        {% endblock portfolio %}

        {% block modal %}
        {% endblock modal %}

        {% block contact_us %}
        {% endblock contact_us %}

      </div>
      <div style="height: 75px"></div>
  </main>
<!-- FIX FOOTER -->
<nav class="navbar fixed-bottom navbar-dark bg-nav-color">
  <a class="navbar-brand mr-4 bottomOfPage_left" href="#">
    <i class="fas fa-sort-up"></i></a>

    <div class="text-center">



          {% if title == "Bio"%}
             <p class="text-left" style="color:#cccccc">Made with <a class="" href="https://phoebx.com" target="_blank"><i class="far fa-heart"></i></a> by <a class="" href="https://github.com/punctuationmarks" target="_blank">punctuationmarks</a></p>

          {% else %}

            <a class="pad" href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-f"></i></a>
            <a class="pad" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a>
            <a class="pad" href="https://github.com/punctuationmarks" target="_blank"><i class="fab fa-github"></i></a>
            <a class="pad" href="{{ url_for('main_bp.contact')}}"><i class="fas fa-mail-bulk"></i></a>
            <a class="pad" href="{{ url_for('main_bp.map')}}" target="_blank"><i class="far fa-map"></i></a>

          {% endif %}

    </div>



        <a class="navbar-brand text-right bottomOfPage_right" href="#"><i class="fas fa-sort-up"></i></a>
    </nav>


  <!-- BOOTSTRAP 4 -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/main.js')}}"></script>
</body>
</html>